### ISSUE TITLE
Make recipes available without authentication

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing.org#10]
The idea is that people can share the link to their recipe, and you'd be able to see them without the need for an account.

Currently, browsing to a recipe page redirects to the login page.

**Comment by kieranklaassen** [comment]
@joostdecock Do you want this to be a private link? So if you want to share it we add a secret key for authentication? Or just the full url with token as it is in the browser when logged in?

**Comment by joostdecock** [comment]
No, I think it's fine to just make the URL accessible without authentication.
The backend already allows reading of recipes without authentication anyway.

The idea is that people can share a recipe, and seeing it does not require an account.

I'm also pretty sure this is already implemented in the page itself, but it might break because of some assumption about a user being logged in somewhere in the component tree.

Here's a recipe: https://en.freesewing.org/recipes/oalpy
It loads the homepage when I browse it in incognito mode, and throws a bunch of errors in the console.

I'll take this one as it's perhaps a bit of a PITA
