### ISSUE TITLE
Chat link needs updating

### ISSUE THREAD

**Issue by DocSpencer77** [freesewing/freesewing.org#1023]
Sorry I can’t seem to locate the code for the “links” section %)

We should change the “CHAT: gitter.im/freesewing” link to dicord… but the links don’t seem generalized…
https://discord.com/channels/698854858052075530/698854858496802868
that one is to the ~main text-chat thing… but what do you want to link to?

Sorry I’m not helping that much… just acting clueless, pretty much . %)
![image](https://user-images.githubusercontent.com/43393580/94094494-3e226100-fde5-11ea-9429-1b580e6c78d5.png)

**Comment by joostdecock** [comment]
Always link to: https://chat.freesewing.org/
I've fixed it.
