### ISSUE TITLE
Slider pattern options slider doesn't update draft, only clicking does

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing.org#104]
When sliding a slider option, it does update the displayed value, but it does not update the (gist in the) state, and thus doesn't actually apply the value.

This is an issue with how we handle the slider. When you slide it, it updates the value constantly, so re-rendering for every update would trash performance. Instead, we re-render only when the sliding stops.

Or at least that's the plan. Obviously there's an issue here.

**Comment by jliu1016** [comment]
I'm sliding the options and it seems to be working, I see the pattern being actively updated whenever I stop sliding.

**Comment by joostdecock** [comment]
The exact behavior depends a bit on the browser, and what events it fired.
But I've figured it out, it's fixed in this commit: https://github.com/freesewing/freesewing/commit/ca64ff8a10bc77a92a8c5680a605e519d0e63eb6

(it's really a one-line fix, but there's also auto-formatting going on
