### ISSUE TITLE
Show both defaults and recipe defaults in different color

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing.org#106]
When configuring your pattern, you can see what options are non-default because they are styled differently.

The idea here is that when you re-create a recipe, you would have an indication that your option is different from the recipe you started from (rather than different from the pattern default).

**Comment by jliu1016** [comment]
Joost, do you remember the user that requested this feature? A good tip my Project Manager mentor gave me is to figure out the painpoint + problem and then figure out what to do to solve it (or confirm that their idea is the best course of action). (Instead of them telling you what to do)

**Comment by joostdecock** [comment]
It was a twitter user, so I can't mention him. But [here's a link to that specific message in the chat](https://gitter.im/freesewing/chat?at=5d705ebec59390272014147e)
I'll mention them in the chat :)

**Comment by joostdecock** [comment]
Alright, let's take a deep dive into what it would take to make this happen.

On the frontend, the draft is configured through a component aptly name `DraftConfigurator`. This is a shared component (it's part of the `@freesewing/components` package, because we use the same component in the stand-alone development environment that is created by `npm init freesewing-pattern`.

This comonent is loaded (in `src/components/draft/draft.js` as such:

```js
<DraftConfigurator                        
  recipe={recipe.recipe}                  
  gist={props.gist}                       
  units={props.app.account.settings.units}
  config={pattern.config}                 
  updateGist={props.updateGist}           
  raiseEvent={raiseEvent}                 
/>                                        
```

There's two takeaways here:

 - This can't be fixed in the freesewing.org repo, but must be fixed in the freesewing repo
 - The `DraftConfigurator` component already had all the info it needs to do this. Because it has both the actual config (this is the `gist` and the recipe it is based on `recipe`)

When we look at [the DraftConfigurator source code](https://github.com/freesewing/freesewing/tree/develop/packages/components/src/DraftConfigurator), you'll see that there's a lot going on there. However, most of it is to deal with different types of options. And the part that we are interested in is shared between all of them. It is the [OptionPreamble](https://github.com/freesewing/freesewing/tree/develop/packages/components/src/DraftConfigurator/OptionPreamble).

 The actual styling of a non-default option happens on [this line](https://github.com/freesewing/freesewing/blob/develop/packages/components/src/DraftConfigurator/OptionPreamble/index.js#L35):

```js
 let displayClass = props.value === props.dflt ? "dflt" : "custom";
```

The `OptionPreable` component gets the current value and the default value as props. And if they differ, it applies the `custom` CSS class to them. If they don't the `dflt` CSS class is used.

This means we need to go up in the component tree to address the issue, but also that we've got two options here:

 - Make the `dflt` that is passed down with props the recipe default, rather than the pattern default
 - Add an extra prop with the recipe default so we can apply 3 different style:
  - Recipe default
  - Pattern default
  - Custom

I think that if we're doing this, we should go with the latter.

Even though the default value is passed down in props, we're lucky in the sense that we don't have to go make changes in the components of every option type. Because they merely pass the props down that they get from the `OptionGroup` component ([link](https://github.com/freesewing/freesewing/blob/develop/packages/components/src/DraftConfigurator/OptionGroup/index.js#L22)) :

```js
dflt: optionDefault(name, props.config.options[name], props.recipe),
```

`optionDefault` is a method in the `@freesewing/utils` package that gives the default value for a given option of a pattern.
We'd just have to add a prop to pass down the default value in the recipe, make sure that props is passed down all the way to the `OptionPreamble` component, and then change the code to apply the correct CSS class.

If an option is not present in a recipe, or if it's not a re-create at all, we can probably just pass down the default value instead, and make sure that if recipe and pattern defaults are identical, the pattern default CSS class takes precedence.

So, all in all this is not really that hard to fix. But it will require you to setup both the website repo and the monorepo locally to test this.

**Comment by joostdecock** [comment]
I think we might roll out a new version next weekend. Do you think there's any chance you have time for this before that @jliu1016 ?

I can try to work on it too, but I know you wanted this. So just checking to see whether you'll have time for it or not.

**Comment by joostdecock** [comment]
Done :)
