### ISSUE TITLE
Can't export pattern bug

### ISSUE THREAD

**Issue by jwill** [freesewing/freesewing.org#110]
Steps to repro:
1. Create new pattern.
2. Select Export Pattern.
3. All options under Export for Printing, and Export for Editing-> Postscript, PDF return  Backend or network seems down error message [seems to be anything that uses tiler]

Inspecting the console shows 
```
Failed to load resource: net::ERR_CERT_DATE_INVALID       tiler.freesewing.org/api:1
```
```
Error: Network Error                                        useTiler.js:18 
    at e.exports (createError.js:17)
    at XMLHttpRequest.d.onerror (xhr.js:88)
```

**Comment by jwill** [comment]
Seems to have been a temporary thing...working again.

**Comment by joostdecock** [comment]
The certificate had expired, but it's fixed now. Thanks for reporting this!
