### ISSUE TITLE
Incorrect estimate units on measurement entry pages

### ISSUE THREAD

**Issue by jwill** [freesewing/freesewing.org#234]
Steps to reproduce:
1. Have account units set to imperial.
2. Enter or change a measurement.

Displayed page shows the cm estimate with symbol for inches. 
![image](https://user-images.githubusercontent.com/66931/66684727-8fb2f980-ec2f-11e9-8512-f04f7ccb48e0.png)

**Comment by joostdecock** [comment]
Good catch :+1:

**Comment by joostdecock** [comment]
Fixed in v2.1.1, deploy pending
