### ISSUE TITLE
Styling of tiers is off

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#24]
<img width="1912" alt="https___en_freesewing_org" src="https://user-images.githubusercontent.com/209089/62944717-ebcdde80-bda2-11e9-892c-fe15b99ffa2f.png">

- [ ] Fix max-width of grid container
- [ ] Fix height of free tier

**Comment by joostdecock** [comment]
The free tier is supposed to be full-width:

![Screenshot_2019-08-13 https 5d3a19f370cf17000847968d--fs-org-en netlify com](https://user-images.githubusercontent.com/1708494/62949320-46d4f500-bde6-11e9-8d36-6baae9ce54c1.png)

This deploy preview still has that layout: https://5d3a19f370cf17000847968d--fs-org-en.netlify.com/

**Comment by joostdecock** [comment]
FYI the layout as shown above only needs `display: inline-flex` to be applied to those colored boxes.
That keeps them the same height it seems

**Comment by kieranklaassen** [comment]
I'm trying to do everything with the stock material-ui without any custom css. I am only familiar with bootstrap so I need to figure it out a bit

**Comment by joostdecock** [comment]
Ah ok, I understand. See, I never used mui's **Grid** component:

```
grep -R Grid src/
src/components/subscribe/index.js:import Grid from '@material-ui/core/Grid'
src/components/subscribe/index.js:    <Grid id="tiers" container spacing="2" alignItems="stretch">
src/components/subscribe/index.js:        <Grid item sm="12" md>
src/components/subscribe/index.js:        </Grid>
src/components/subscribe/index.js:      <Grid item sm="12" md>
src/components/subscribe/index.js:      </Grid>
src/components/subscribe/index.js:      <Grid item sm="12" md>
src/components/subscribe/index.js:      </Grid>
src/components/subscribe/index.js:      <Grid item sm="12" md>
src/components/subscribe/index.js:      </Grid>
src/components/subscribe/index.js:    </Grid>
```

I find it too clunky and it fixes a problem that I feel is better handled in CSS.
But if you're used to Bootstrap, I get that the 12-column grid is familiar :)

If we avoid using Grid, webpack will tree-shake it out of our bundle. So I do prefer that option. But I also don't want to be all *my way or the highway* about it either

**Comment by kieranklaassen** [comment]
I would really prefer to use a framework for this since writing CSS seems a little low level. If we use the grid we simplify mobile responsive layouts and other things we do not have to think about anymore. Also, if other developers jump in they understand everything right away. Now it is kind of a journey to see how the CSS is working. Either way, I'll fix this layout and we can discuss the usage of design frameworks some other time too and the pros and cons.

**Comment by joostdecock** [comment]
They way I see it is that the UI framework is for consistent styling. Buttons, forms, that sort of thing.
But the *grid* approach to layout seems like more hassle than it's worth when we have flexbox and css grid. Then again, I like CSS :)

It's true that it's a more general topic. And there's no rights and wrongs here. 
For what it's worth, allow me to share that you have `props.app.frontend.mobile` and `props.app.frontend.tablet`. You can check these and apply specific styles for those viewports in your component. Just FYI

**Comment by joostdecock** [comment]
That was some quality work you did Kieran :clap: :clap: I never got really familiar with that mui `makeStyles` approach, so this was a good learning experience for me :smiley: 

Also, that ` { varlable && <Component /> } ` stuff :arrow_right: great! I had been writing ` { variable ? <Component /> : null } ` this entire time like some schmuck :laughing: Every day is a school day!

Just a heads-up that I tweaked the homepage a bit for different viewports, and while I was at is also put the last finishing touches on the *subscribe* boxes:

![Screenshot_2019-08-15 Screenshot](https://user-images.githubusercontent.com/1708494/63094510-efab5d80-bf68-11e9-96e7-11fe84228b0f.png)

Thanks again for showing me how the grownups do it :+1:
