### ISSUE TITLE
Change the landing page picture

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#381]
Maybe we can update the landing page picture to more tailer to the custom/tech/sewing/fun/open vibe. Maybe our little robot guy could take part in it? Maybe even animated? If someone has ideas, knows a designer. I think it could add to the initial experience of Freesewing.

<img width="1917" alt="FreeSewing" src="https://user-images.githubusercontent.com/209089/70164683-3abbbe80-1687-11ea-9616-9fb67507e033.png">

**Comment by joostdecock** [comment]
I feel the homepage in general is a bit underwhelming.
I sort of did what I could, but a designer willing to help us out would be godsend.

Unfortunately, I don't know anyone who does UI/UX design, but I am hopeful maybe others will chime in.

There's also https://opensourcedesign.net/jobs/ but I have never used it.
Or perhaps there's a subreddit somewhere that would be a good place to ask?

**Comment by kieranklaassen** [comment]
I can try to see if I can come up with an idea.

**Comment by joostdecock** [comment]
Done by @kieranklaassen  :)
