### ISSUE TITLE
got an error on Simone parttern

### ISSUE THREAD

**Issue by marinaLudi** [freesewing/freesewing.org#413]
Error: Error in Path.shiftAlong(): Ran out of path to shift along. Distance requested was 2, path length is0.88.

Stack trace

AxEy/y.prototype.shiftAlong@https://en.freesewing.org/component---src-components-app-index-js-6369527c3edfda20d7d4.js:1:1598275
AxEy/y.prototype.offset/<@https://en.freesewing.org/component---src-components-app-index-js-6369527c3edfda20d7d4.js:1:1595611
AxEy/y.prototype.offset@https://en.freesewing.org/component---src-components-app-index-js-6369527c3edfda20d7d4.js:1:1596058
o0DT/m.prototype.draftFront@https://en.freesewing.org/component---src-components-app-index-js-6369527c3edfda20d7d4.js:1:3505074
8lb2/rf.prototype.draftFrontBase@https://en.freesewing.org/component---src-components-app-index-js-6369527c3edfda20d7d4.js:1:1361047
AxEy/U.prototype.draft@https://en.freesewing.org/component---src-components-app-index-js-6369527c3edfda20d7d4.js:1:1621735
8lb2/ym<@https://en.freesewing.org/component---src-components-app-index-js-6369527c3edfda20d7d4.js:1:1478695
pi@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:71206
Xi@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:79406
zo@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:117616
Mu@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:101996
Nu@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:101919
ku@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:99259
Jl/<@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:57616
+wdc/t.unstable_runWithPriority@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:3572
ql@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:57326
Jl@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:57564
Gl@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:57497
vu@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:96025
enqueueSetState@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:62276
viRO/w.prototype.setState@https://en.freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:6709
YwZP/w

**Comment by joostdecock** [comment]
Thank you for reporting this @marinaLudi Could you please let us know the username and model you used when bumping into this issue? That will allow us to investigate.

**Comment by joostdecock** [comment]
Just a heads-up: Would it be possible to supply this information?

**Comment by joostdecock** [comment]
Can't fix this without info. Closing.
