### ISSUE TITLE
Simon Shirt pattern - issue, help

### ISSUE THREAD

**Issue by MakerMikeA** [freesewing/freesewing.org#416]
I tried to redo my simon shirt - i changed a couple of measurements and got this... I tried to go to pattern and select model and it still will not create....any reason why.

![5D6ECEFE-705C-4244-9355-24183B1E545B](https://user-images.githubusercontent.com/46345731/70869166-f7632900-1f7f-11ea-8d27-066a52a83110.png)

**Comment by joostdecock** [comment]
Hmm, that's not good. Might be a regression bug introduced in 2.1.7. I'll look into it.

**Comment by joostdecock** [comment]
Fixed :)

**Comment by MakerMikeA** [comment]
Will try again...Thanks for looking and sorting it out. Your just tooo good. 😇😇👏
