### ISSUE TITLE
See if we can use SSR for all pages

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#43]
Since we use gatsby, we should consider using SSR for version 2.1 for all pages. This will improve page load, lighthouse audit a lot.

<img width="513" alt="https___en_freesewing_org" src="https://user-images.githubusercontent.com/209089/63624926-a93aac00-c5c3-11e9-9be6-1797817e5582.png">

**Comment by joostdecock** [comment]
We already have SSR (Gatsby does it out of the box). At least for pages we can create at build time (not for user profiles and so on).

I'm closing this in favor of more speficic enhancements (such as PWA)
