### ISSUE TITLE
Error trying to make the Florent flat cap (iPhone/iOS, Safari).

### ISSUE THREAD

**Issue by gad-o-lin** [freesewing/freesewing.org#468]
Head circumference was configured for the model. After selecting “new Florent” and then tapping on the model avatar icon, the error message came up.

Error: Error in Path.shiftAlong(): Ran out of path to shift along. Distance requested was 2, path length is0.

https://freesewing.org/component---src-components-app-index-js-f31b1604caa5804532c6.js:1:1603542
https://freesewing.org/component---src-components-app-index-js-f31b1604caa5804532c6.js:1:1600879
https://freesewing.org/component---src-components-app-index-js-f31b1604caa5804532c6.js:1:1171441
https://freesewing.org/component---src-components-app-index-js-f31b1604caa5804532c6.js:1:1627009
https://freesewing.org/component---src-components-app-index-js-f31b1604caa5804532c6.js:1:1484292
pi@https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:71207
Xi@https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:79408
Mu@https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:101996
Nu@https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:101921
ku@https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:99261
ku@[native code]
https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:57617
https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:3573
Jl@https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:57564
Gl@https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:57499
vu@https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:96027
enqueueSetState@https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:62278
https://freesewing.org/commons-5d52e3a4cf5c225298d9.js:1:6724
https://freesewing.org/app-452b1c716496ef43251d.js:1:77656

**Comment by joostdecock** [comment]
Thank you for reporting this @gad-o-lin Could you share your username on the site and the model you made this for? That would allow us to reproduce this.

thanks
joost

**Comment by gad-o-lin** [comment]
Hi @joostdecock – my username is gadolin on the site.

There are two models on my account, "Jani" and "Imperial Jani". I created a new model with imperial units to test whether the issue was with units conversions as the error message included "paths" and "distances". The model "Jani" is in metrics. However, the same issue happened regardless of the unit system chosen.

I tried creating the Florent also on my laptop with Chrome. The exactly same issue happened again, so it does not seem to be iOS or Safari.


Best
Jani

**Comment by joostdecock** [comment]
Tx Jani, I'll look into this asap :)

**Comment by gad-o-lin** [comment]
Tnx!

**Comment by joostdecock** [comment]
I've made some changes to Florent to address this issue. They are part of the upcoming 2.2 release which I hope will be out later this week.

I'm going through the issues to see if we've missed anything, so I'm closing this. However, you'll have to wait for 2.2 to come out to find the fix on the website.

**Comment by gad-o-lin** [comment]
Sounds good, thanks!

**Comment by joostdecock** [comment]
2.2.0 is now published on https://freesewing.org/

**Comment by gad-o-lin** [comment]
Works like a charm! Thanks.
