### ISSUE TITLE
Path length is 0.

### ISSUE THREAD

**Issue by lkdurvin** [freesewing/freesewing.org#493]
I only have one measurement, head circumference, and I want to see a small file. I tried to make a Florent hat. I got the error "Error in Path.shiftAlong(): Ran out of path to shift along. Distance requested was 2, path length is0."

**Comment by joostdecock** [comment]
Could you share what the head circumference was, that would allow us to reproduce this.

thanks

**Comment by lkdurvin** [comment]
It is 22 3/4". Preferences are in inches.

*--*
Kent Durvin
804.317.3454

**Comment by joostdecock** [comment]
This is fixed in the upcoming 2.2 release that should come out later this week.

**Comment by joostdecock** [comment]
2.2.0 is now published on https://freesewing.org/
