### ISSUE TITLE
No measure square for any of the patterns

### ISSUE THREAD

**Issue by ZoeJC** [freesewing/freesewing.org#511]
How do I know that these patterns are true to size when there is not a 2x2 square to check that it's printed true?

**Comment by joostdecock** [comment]
Look for this box:

![Screenshot_2020-02-17 Recreate test for Size 34, With breasts](https://user-images.githubusercontent.com/1708494/74633702-83512700-5162-11ea-887e-20617486ebdf.png)

As it says at the bottom:

> The inside of this box should measure 10cm x 5cm 
> The outside of this box should measure 4" x 2"
