### ISSUE TITLE
Breanna shows up in pattern filter prior to release

### ISSUE THREAD

**Issue by ricekream** [freesewing/freesewing.org#515]
Breanna only shows up in search results and page does not open. Is there an issue there or is it on my end?

**Comment by joostdecock** [comment]
Breanna is part of our upcoming 2.2 release. It shouldn't show up on the site until 2.2 is out.
Where did you stumble across it?

**Comment by ricekream** [comment]
In the patterns search. If i use the womenswear search filter or block search filter. When is 2.2 set to release?

**Comment by joostdecock** [comment]
Ah, I guess the pattern's metadata seeped into the current release.

2.2 is almost ready and you can preview it at https://next.freesewing.org/
I still need to put in a few tweaks to Breanna, and @kieranklaassen is working on the homepage.
After that, it's just QA and then we can push it out.

If you'd like to keep up to date with what we're working on, you are very welcome to stop by our developers chat room: https://gitter.im/freesewing/development  (it's not only for developers, just for people with an interest on what's going on behind the scenes).

**Comment by ricekream** [comment]
Cool!! Thanks!

**Comment by joostdecock** [comment]
Breanna is about ready, I hope to release 2.2 later this week. Closing this.

**Comment by joostdecock** [comment]
2.2.0 is now published on https://freesewing.org/

**Comment by ricekream** [comment]
You guys are amazing!!! You have made a subscriber out of me

**Comment by joostdecock** [comment]
*blush* thank you :pray:
