### ISSUE TITLE
errors.requestFailedWithStatusCode413 Paperless Simon 

### ISSUE THREAD

**Issue by ToastSeagers** [freesewing/freesewing.org#516]
When trying to export a Simon pattern with paperless enabled, I get the following error. 

![image](https://user-images.githubusercontent.com/61140937/74639015-bbae3080-5175-11ea-8d46-fde073b98fb1.png)

**Comment by ToastSeagers** [comment]
Username=Toast, Model=Toast, Pattern=Simon

**Comment by joostdecock** [comment]
Thank you for reporting this. It was due to an request size limit in our tiling backend.
It's fixed now.
