### ISSUE TITLE
Unable to save recipe

### ISSUE THREAD

**Issue by ZoeJC** [freesewing/freesewing.org#524]
Hi

Sorry if this function has been removed, I'm no longer able to save recipes in my pattern section?

**Comment by joostdecock** [comment]
To save the pattern, click the blue **Share pattern** button next to the Black **Export pattern** button:

![Screenshot_2020-02-23 New benjamin for Toya Jaeger](https://user-images.githubusercontent.com/1708494/75109756-dd506180-5626-11ea-8b21-14b4b4beaf4d.png)

Let me know if that doesn't work somehow.
