### ISSUE TITLE
After exporting, no way back

### ISSUE THREAD

**Issue by ToastSeagers** [freesewing/freesewing.org#525]
After exporting a pattern there is no obvious way to get back to either edit or save a pattern. If you press the browser back button it takes you back an entire stage to choosing the model again and loses any changes you might have made to style and fit. 

Username - Toast
Pattern - Simon
Model - Toast
Browser - Firefox

https://www.loom.com/share/d45503a58d4a416b85d542669337094d

**Comment by joostdecock** [comment]
Thank you for this detailed report. We should handle that better and preserve state somehow.

I'll have to think about this, but we'll try to do better.

**Comment by joostdecock** [comment]
We've rolled-out a UX updated on https://next.freesewing.org/ that addresses this issue.

It's not in production yet, for we need to run some more tests, but you can already try it out there.

**Comment by ToastSeagers** [comment]
That interface looks great and should work really well. I'll leave the ticket open for you to close once you are satisifed that you have tested it properly. A few basic checks from my side show it all working.

**Comment by joostdecock** [comment]
These changes are now deployed.
