### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by corvus-ch** [freesewing/freesewing.org#536]
I am trying to create a new account.

Given I have filled in and submitted my data for a new account
And I have received the email with the confirmation link 
When follow the link "Confirm your E-mail address"
And I check "Do you give your consent to process your profile data?" with "Yes, I do"
And I check "Do you give your consent to process your model data? with "Yes, I do"
And I press "Create my account"
Then nothing visible happens.

On the console, I see the output:

```
ReferenceError: setResult is not defined_confirmation.js:36:6
    onClick _confirmation.js:36
    React 12
        h
        k
        T
        T
        j
        A
        O
        Pn
        ue
        jn
        zn
        On
    bind_applyFunctionN self-hosted:1054
    On self-hosted:1018
    unstable_runWithPriority scheduler.production.min.js:274
    React 3
        Go
        se
        An
    An self-hosted:977
    __trace__ bugsnag.js:2435
```

**Comment by joostdecock** [comment]
That doesn't sound good. I'll have a look at this ASAP

**Comment by joostdecock** [comment]
Fix has been committed. As soon as [this build](https://app.netlify.com/teams/freesewing/builds/5e539c4137383d0007aab090) is finished, the issue will be resolved.

Thanks for reporting this!

**Comment by corvus-ch** [comment]
Thanks for the fast fix. I can confirm this to be fixed. At least it worked for me.
