### ISSUE TITLE
Github login error

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#56]
Also, log in with Github is busted https://freesewing.org/login
error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.

**Comment by jliu1016** [comment]
Still getting an unauthorized page after logging in.

"https://backend.freesewing.org/oauth/callback/from/github?code=66d04a7667619a69d487&state=5d72ddc66585f91d0418644e"

**Comment by joostdecock** [comment]
Closing again :) (because I fixed it)
