### ISSUE TITLE
Broken link on freesewing.org

### ISSUE THREAD

**Issue by caitelatte** [freesewing/freesewing.org#604]
Please include the URL of the page that has the broken link on it:

Was sent to https://en.freesewing.org/docs/about/model-graph from the Documentation button on the _Start with your neck circumference_ popup on a new person model page [https://en.freesewing.org/people/jxhdq/](https://en.freesewing.org/people/jxhdq/)

![Screenshot_2020-03-18 Caitlin](https://user-images.githubusercontent.com/4994062/76913056-fee0f800-6909-11ea-9b28-2857d5ca6159.png)

**Comment by joostdecock** [comment]
Thanks for reporting this @caitelatte

**Comment by joostdecock** [comment]
The correct link is https://en.freesewing.org/docs/about/your-measurements/model-graph
Fixed in the develop branch, will roll it out in production with some other small changes later today.
