### ISSUE TITLE
Sign up with Github not working 

### ISSUE THREAD

**Issue by thirtythreedown** [freesewing/freesewing.org#627]
Hello everybody. 

Website fails to create new account from https://freesewing.org/ using "Signup with Github" option. See screenshots attached.

Browsers tested: Firefox, Chrome (latest stable versions).
Cache cleaned.

![freesewing_githubbug_1](https://user-images.githubusercontent.com/32502009/77802335-a5cf3d80-7048-11ea-8caf-efc26de5554a.png)
![freesewing_githubbug_2](https://user-images.githubusercontent.com/32502009/77802338-a667d400-7048-11ea-8baf-79d209a462d8.png)
![freesewing_githubbug_3](https://user-images.githubusercontent.com/32502009/77802339-a7006a80-7048-11ea-8e28-39a7b199942b.png)
![freesewing_githubbug_4](https://user-images.githubusercontent.com/32502009/77802340-a7006a80-7048-11ea-9955-596f361c0900.png)

**Comment by joostdecock** [comment]
Ok, I figured out what's causing this. The Github users API does not always return an email address:

> The email key in the following response is the publicly visible email address from your GitHub profile page. When setting up your profile, you can select a primary email address to be “public” which provides an email entry for this endpoint. If you do not set a public email address for email, then it will have a value of `null`.

So it doesn't work for you because your email address is not listed. It works for me because it is.

We'll need to detect this edge-case, and make another API call to fetch the email address specifically. I'll need to work on this.

**Comment by joostdecock** [comment]
Note that I've created this issue for this: https://github.com/freesewing/backend/issues/162
It's a backend bug, so I'm closing this issue in favour of that one.
