### ISSUE TITLE
Crash with Jager

### ISSUE THREAD

**Issue by GitBen2** [freesewing/freesewing.org#64]
trying to set 2 vents at 60% on Jager (similar to last version). The initial problem was that the sliders did not update the pattern. I initially used chrome with no luck and switched to edge to see if it was a browser problem. Edge actually worked better initially (strangely) and then the Jager java script crashed.

**Comment by joostdecock** [comment]
Thanks for reporting this. I was able to confirm it. We'll look into it.

Also, the number of vents shouldn't be a slider but a radio button list. I'll create an issue for that too.

**Comment by joostdecock** [comment]
I'm closing this because the actual problem is in the [freesewing](https://github.com/freesewing/freesewing) repository, so I've created an issue there instead: https://github.com/freesewing/freesewing/issues/76

@GitBen2 You can subscribe to the issue linked above to receive updates.

**Comment by joostdecock** [comment]
Slider issue is here: https://github.com/freesewing/freesewing/issues/77
