### ISSUE TITLE
Add "New pattern" link/button on the patterns pages

### ISSUE THREAD

**Issue by Slylele** [freesewing/freesewing.org#645]
It would be nive to get direct access to pattern creation when we are consulting pattern informations. Here is my proposal, but on main page, simple link would be enough.
![Proposition_amelioration_New_pattern](https://user-images.githubusercontent.com/57619777/78499924-ee2ae180-7753-11ea-8bf3-52e398e34a31.png)

**Comment by joostdecock** [comment]
I've added the button. The entry in the menu is a bit tricky, because the menu represent the hierarchy of the documentation, so I'm going to leave that as is.

**Comment by joostdecock** [comment]
Sorry, forgot the screenshot:
![Screenshot_2020-04-05 Aaron A-Shirt](https://user-images.githubusercontent.com/1708494/78502415-6a77f180-7761-11ea-9faf-2b383ba301e0.png)

**Comment by joostdecock** [comment]
You can preview these changes here: https://next.freesewing.org/
