### ISSUE TITLE
Pattern Export

### ISSUE THREAD

**Issue by GitBen2** [freesewing/freesewing.org#65]
Pattern exporting to pdf is failing for (at least) Jager, Theo, Benjamin and Simon. Pattern pieces overlapping and pieces not arranged on the page. There is an interesting version of this failure on edge where the simon pattern pieces are all printed on three pieces of A4 paper.

**Comment by joostdecock** [comment]
I've pushed a [fix for this](https://github.com/freesewing/freesewing.org/commit/f78278f9acb96c53dab0c150599a8229e9d99b29) that should get deployed soon.

**Comment by joostdecock** [comment]
Fix confirmed, deployed in production.
