### ISSUE TITLE
Issue on Ankle measurement picture

### ISSUE THREAD

**Issue by Slylele** [freesewing/freesewing.org#657]
I think there is an issue on the "yellow marks" set on the picture for Ankle measurements
![image](https://user-images.githubusercontent.com/57619777/79049879-7b73a780-7c26-11ea-8add-98dd5638f968.png)

**Comment by joostdecock** [comment]
Well, spotted! Thanks for reporting this.

**Comment by Slylele** [comment]
These are the marks for men...

Here is the code I think correct but I'm not sure I can correct the svg file because that's not something I'm use to do (I'm afraid to make a mistake)
I've changed <path> and <g></g> coordonates....
---------------------------------------------------------------------------------------

<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" width="2000" height="1500" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2000 1500">
    <defs>
        <path id="path" d="M 0 0 c 20 2 20 2 42 0 m -838 -20 l 44 -8 m -640 30 l 54 0" style="fill: none; stroke-linejoin: round;"/>
    </defs>
    <style type="text/css"><![CDATA[
        path {fill: none; stroke-linejoin: round;}
        .tape {stroke: #000; stroke-width: 20px; stroke-linecap: butt;}
        .redtape {stroke: #f00; stroke-width: 1px;stroke-linecap: round;}
        .color {stroke: #fff86c; stroke-width: 16px; stroke-linecap: butt;}
        .cm {stroke: #000; stroke-width: 16px; stroke-dasharray: 2 10; stroke-linecap: butt;}
    ]]></style>

    
    <image xlink:href="./standing.jpg" x="0" y="0" width="2000" height="1500" />

    <g>
        <use x="1660" y="1290" xlink:href="#path" class="redtape">
            <animate attributeType="CSS" attributeName="stroke-width" from="1" to="450" begin="loop.begin+2.5s" dur="0.5s" fill="freeze" />
            <animate attributeType="CSS" attributeName="stroke-opacity" from="1" to="0" begin="loop.begin+2.7s" dur="0.3s" fill="freeze" />
        </use>
        <use x="1660" y="1290" xlink:href="#path" class="tape"/>
        <use x="1660" y="1290" xlink:href="#path" class="color"/>
        <use x="1660" y="1290" xlink:href="#path" class="cm"/>
    </g> 

    
    <rect height="1" width="1" x="-10" y="-10">
        <animate attributeType="CSS" attributeName="visibility" from="hide" to="hide" begin="0;loop.end" dur="4s" id="loop" />
    </rect>

</svg>

---------------------------------------------------------------------------------------

Here is the result on my computer:

![image](https://user-images.githubusercontent.com/57619777/79053685-73743180-7c3f-11ea-8e4c-63c4c680d8ef.png)

**Comment by joostdecock** [comment]
Nice work. The fix has already been deployed :)
