### ISSUE TITLE
Pattern drafting

### ISSUE THREAD

**Issue by GitBen2** [freesewing/freesewing.org#66]
Jager pattern: When the number of back vents is set to 2 pattern piece 3 and pattern piece 2 don't have matching vent lengths. 

There appears to be a seam allowance problem on pattern piece 3 (becomes apparent with two vents and 49.4% vent length - creates a crash condition for other settings).

**Comment by joostdecock** [comment]
Dupe of https://github.com/freesewing/freesewing/issues/76 which has been fixed.
