### ISSUE TITLE
Breanna body block

### ISSUE THREAD

**Issue by gemcal** [freesewing/freesewing.org#663]
Hi! I'm very excited to try the breanna body block, but when I try to generate a pattern to suit my measurements, it comes up with the following error:

TypeError: o.scyeDart1.shiftTowards is not a function

Thanks for your magnificent website, I've already made the Penelope pencil skirt and it fits like a dream!

**Comment by joostdecock** [comment]
Could you let us know your username on the site, and the person/site you generated breanna for @gemcal ?

**Comment by gemcal** [comment]
Hi Joost,

My username on freesewing is also gemcal and the person is Gemma.

Thanks!

**Comment by joostdecock** [comment]
Thanks, I'll try to have a look after work.

**Comment by joostdecock** [comment]
Breanna issues are now being tracked in #688. Closing in favor of that.
