### ISSUE TITLE
Add prompt explaining that login is required for made-to-measure patterns

### ISSUE THREAD

**Issue by dasnessie** [freesewing/freesewing.org#680]
I recently started using freesewing. Before I signed up, i was very confused about where to enter my measurements to get a made-to-measure pattern because I didn't understand I needed to sign up for that.

I think a prompt on the page where the user chooses the size would help to make that clear. It should only be displayed when the user is not logged in and could read something like this: "You are currently not logged in. Because of that, you can only access a few standard sizes. Log in (link) for access to made-to-measure patterns."

**Comment by joostdecock** [comment]
Seems I forgot to close this, because we added this a while back. Here's a screenshot:

![Screenshot_2020-07-11 Choose a size](https://user-images.githubusercontent.com/1708494/87228781-b6ab8100-c3a3-11ea-8cc2-ea9544469c16.png)

Thanks for reporting this!
