### ISSUE TITLE
Add labels to "compare industry sizes" in preview pattern

### ISSUE THREAD

**Issue by kieranklaassen** [freesewing/freesewing.org#69]
To know what we compare against, add labels for the compare view

**Comment by joostdecock** [comment]
I'm reluctant to hack something into core for this, but we could probably contain this to a plugin using the `postSample` hook.

I'll have to look at this in detail, just sharing my thoughts :)

**Comment by joostdecock** [comment]
This has been implemented in v2.7.0-beta.2. Here's a screenshot:

![Screenshot_2020-07-11 New Aaron A-Shirt for Size 42, Without breasts](https://user-images.githubusercontent.com/1708494/87228880-7bf61880-c3a4-11ea-97f1-dcf3867eea1e.png)
