### ISSUE TITLE
"Save As New Pattern" Not Working

### ISSUE THREAD

**Issue by marygraceblair** [freesewing/freesewing.org#730]
Issue happens when you try to use the "Save As New Pattern" button on an existing pattern. 

<img width="946" alt="Screenshot 2020-06-10 14 11 03" src="https://user-images.githubusercontent.com/13790422/84308523-48fe0200-ab24-11ea-9f6f-648f24c4119d.png">

**Comment by joostdecock** [comment]
Thanks for reporting this Mary, I'll have a look.

**Comment by joostdecock** [comment]
Thanks for reporting this. The fix is currently being deployed.

Don't hesitate to create a new issue if you can break it again :)
