### ISSUE TITLE
Make patrons tier boxes the same height

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing.org#8]
See: https://en.freesewing.org/patrons/join

![issue5](https://user-images.githubusercontent.com/1708494/62424282-18ac3280-b6cd-11e9-9f91-5c033d9f9edc.png)

**Comment by kieranklaassen** [comment]
I'll take this one to see the dev flow a bit more

**Comment by joostdecock** [comment]
Great 😀 here's a good place to start:https://github.com/freesewing/freesewing.org/tree/master/src/components/subscribe
