### ISSUE TITLE
Broken Link In Carlton

### ISSUE THREAD

**Issue by GitBen2** [freesewing/freesewing.org#81]
The link to the Carlita pattern instructions from the Carlton documentation page is broken. The current link is: 

https://freesewing.org/en/docs/patterns/carlita

I believe that it should be:

https://freesewing.org/docs/patterns/carlita/instructions

**Comment by joostdecock** [comment]
Thanks for reporting this.
This has been fixed (in the markdow repo). It will appear on the next deploy (which should happen later today.
