### ISSUE TITLE
Problem with New TItan trouser block

### ISSUE THREAD

**Issue by oelrich** [freesewing/freesewing.org#863]
When creating a new Titan from measurements something fails.

---
Oh no!

There was an unexpected problem. Please report this.

TypeError: d.waistIn is undefined

Stack trace

a@https://freesewing.org/4d90dbe830f6af6b1b9b218343a74e4baa7daf3e-43bd69f90b61fc2c958a.js:1:433589
1/vG/so.prototype.draftFront/<@https://freesewing.org/4d90dbe830f6af6b1b9b218343a74e4baa7daf3e-43bd69f90b61fc2c958a.js:1:435799
1/vG/so.prototype.draftFront@https://freesewing.org/4d90dbe830f6af6b1b9b218343a74e4baa7daf3e-43bd69f90b61fc2c958a.js:1:438642
AxEy/J.prototype.draft@https://freesewing.org/4d90dbe830f6af6b1b9b218343a74e4baa7daf3e-43bd69f90b61fc2c958a.js:1:599235
rlTK/t.a@https://freesewing.org/a550341fd3272bdc56bf5664c5e7ad30c4db79b0-ceac1b2268d30bbfeaff.js:1:48884
Ki@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:70018
Fa@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:78879
vo@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:117476
cu@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:108807
ou@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:108730
Zo@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:105760
Hl/<@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:57402
KqkS/t.unstable_runWithPriority@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:4696
jl@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:57111
Hl@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:57349
Bl@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:57282
vu@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:114482
KqkS/t.unstable_runWithPriority@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:4696
jl@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:57111
hu@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:114134
mu/<@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:114045
U@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:3636
KqkS/T.port1.onmessage@https://freesewing.org/framework-aa5d88264b3232f630b4.js:1:2392

**Comment by joostdecock** [comment]
Thanks for letting us know @oelrich Would you mind sharing your username on the site so I can reproduce this?

**Comment by oelrich** [comment]
Of course, sorry. It's oelrich and it's the only measurement collection.

**Comment by joostdecock** [comment]
Thank you. I'm not saying it's causing this issue, but could you please double-check a few things for me:

- **Waist to knee** : Based on your **Waist to upper leg** measurement, this tells us your knees are 15cm below the top of your leg. Which feels like you perhaps measured wrong?
- **Seat back**: I'm not saying it's wrong, but it feels very unbalanced towards the back in comparison to your waist measurements which are much more 50/50 between back and front.

If we're certain we've got the measurements right, I'd be happy to dive into this.

**Comment by oelrich** [comment]
That does sound a bit peculiar for me, yes. I will go through my measurements again and see if I can get more reasonable values. I'll close this with the assumption that I made a few misstakes.

**Comment by joostdecock** [comment]
> I'll close this with the assumption that I made a few misstakes.

I think you're too kind, but I appreciate the approach. Please don't hesitate to open a new issue when the time comes.
