### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing.org#9]
See https://www.gatsbyjs.org/docs/add-404-page/

**Comment by kieranklaassen** [comment]
I'll pick this one up too

**Comment by joostdecock** [comment]
I've put a 404 on freesewing.dev : https://freesewing.dev/nssjsj

In case that helps

**Comment by joostdecock** [comment]
I've found some uncommitted code lying around that's related to the 404 page 🤔
I'll try to push it in an isolated commit, so it's easy to rip out again if you like.

I'm sorry, I must have started on this at some point but then got sidetracked. I'll try to assign issues next time around.
